### ISSUE TITLE
[app] 在css中控制双端界面

### ISSUE THREAD

**Issue by akinaru-lu** [akinaru-lu/lmm#206]
# 课题
在 https://www.w3schools.com/w3css/tryit.asp?filename=tryw3css_templates_parallax&stacked=h 发现如下代码

```css
/* Turn off parallax scrolling for tablets and phones */
@media only screen and (max-device-width: 1024px) {
    .bgimg-1, .bgimg-2, .bgimg-3 {
        background-attachment: scroll;
    }
}
```
